export const PERMISSIONS = {
  // Expense
  EXPENSE_CREATE: 'expense.create',
  EXPENSE_READ: 'expense.read',
  EXPENSE_UPDATE: 'expense.update',
  EXPENSE_DELETE: 'expense.delete',
  EXPENSE_APPROVE_L1: 'expense.approve_l1',
  EXPENSE_APPROVE_L2: 'expense.approve_l2',
  EXPENSE_EXPORT: 'expense.export',

  // Sale
  SALE_CREATE: 'sale.create',
  SALE_READ: 'sale.read',
  SALE_UPDATE: 'sale.update',
  SALE_DELETE: 'sale.delete',
  SALE_EXPORT: 'sale.export',

  // Payment
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_READ: 'payment.read',

  // Client
  CLIENT_CREATE: 'client.create',
  CLIENT_READ: 'client.read',
  CLIENT_UPDATE: 'client.update',
  CLIENT_DELETE: 'client.delete',

  // Product
  PRODUCT_CREATE: 'product.create',
  PRODUCT_READ: 'product.read',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_DELETE: 'product.delete',

  // Budget
  BUDGET_CREATE: 'budget.create',
  BUDGET_READ: 'budget.read',
  BUDGET_UPDATE: 'budget.update',

  // User Management
  USER_CREATE: 'user.create',
  USER_READ: 'user.read',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',

  // Role Management
  ROLE_CREATE: 'role.create',
  ROLE_READ: 'role.read',
  ROLE_UPDATE: 'role.update',

  // Audit
  AUDIT_READ: 'audit.read',

  // Report
  REPORT_READ: 'report.read',
  REPORT_EXPORT: 'report.export',

  // Dashboard
  DASHBOARD_READ: 'dashboard.read',

  // Cash Closing
  CASH_CLOSING_CREATE: 'cash_closing.create',
  CASH_CLOSING_READ: 'cash_closing.read',
  CASH_CLOSING_VALIDATE: 'cash_closing.validate',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: [...ALL_PERMISSIONS],

  DAF: [
    PERMISSIONS.EXPENSE_READ, PERMISSIONS.EXPENSE_APPROVE_L2, PERMISSIONS.EXPENSE_EXPORT,
    PERMISSIONS.SALE_READ, PERMISSIONS.SALE_EXPORT,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.BUDGET_CREATE, PERMISSIONS.BUDGET_READ, PERMISSIONS.BUDGET_UPDATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CASH_CLOSING_READ, PERMISSIONS.CASH_CLOSING_VALIDATE,
  ],

  CAISSIER_DEPENSES: [
    PERMISSIONS.EXPENSE_CREATE, PERMISSIONS.EXPENSE_READ, PERMISSIONS.EXPENSE_UPDATE,
    PERMISSIONS.EXPENSE_APPROVE_L1,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CASH_CLOSING_CREATE, PERMISSIONS.CASH_CLOSING_READ,
  ],

  CAISSIER_VENTE: [
    PERMISSIONS.SALE_CREATE, PERMISSIONS.SALE_READ, PERMISSIONS.SALE_UPDATE,
    PERMISSIONS.PAYMENT_CREATE, PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_READ, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CASH_CLOSING_CREATE, PERMISSIONS.CASH_CLOSING_READ,
  ],

  COMMERCIAL: [
    PERMISSIONS.SALE_CREATE, PERMISSIONS.SALE_READ,
    PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_READ, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.DASHBOARD_READ,
  ],

  COMPTABLE: [
    PERMISSIONS.EXPENSE_READ, PERMISSIONS.EXPENSE_EXPORT,
    PERMISSIONS.SALE_READ, PERMISSIONS.SALE_EXPORT,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CASH_CLOSING_READ, PERMISSIONS.CASH_CLOSING_VALIDATE,
  ],

  AUDITEUR: [
    PERMISSIONS.EXPENSE_READ, PERMISSIONS.EXPENSE_EXPORT,
    PERMISSIONS.SALE_READ, PERMISSIONS.SALE_EXPORT,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.BUDGET_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CASH_CLOSING_READ,
  ],
};
