/* ═══════════════════════════════════════════
 *  Codes d'erreur standardisés
 * ═══════════════════════════════════════════ */

export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
  INVALID_RCCM_FORMAT: 'INVALID_RCCM_FORMAT',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_AMOUNT: 'INVALID_AMOUNT',

  // Resource
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // Expense
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_ALREADY_APPROVED: 'EXPENSE_ALREADY_APPROVED',
  EXPENSE_CANNOT_BE_EDITED: 'EXPENSE_CANNOT_BE_EDITED',
  EXPENSE_AMOUNT_EXCEEDS_LIMIT: 'EXPENSE_AMOUNT_EXCEEDS_LIMIT',
  EXPENSE_INVALID_STATUS_TRANSITION: 'EXPENSE_INVALID_STATUS_TRANSITION',

  // Budget
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  BUDGET_THRESHOLD_REACHED: 'BUDGET_THRESHOLD_REACHED',
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  BUDGET_PERIOD_OVERLAP: 'BUDGET_PERIOD_OVERLAP',

  // Sale
  SALE_NOT_FOUND: 'SALE_NOT_FOUND',
  SALE_ALREADY_PAID: 'SALE_ALREADY_PAID',
  SALE_CANNOT_BE_EDITED: 'SALE_CANNOT_BE_EDITED',
  SALE_INVALID_STATUS_TRANSITION: 'SALE_INVALID_STATUS_TRANSITION',
  SALE_NO_ITEMS: 'SALE_NO_ITEMS',

  // Payment
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  PAYMENT_INVALID_AMOUNT: 'PAYMENT_INVALID_AMOUNT',

  // Client
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_CREDIT_LIMIT_EXCEEDED: 'CLIENT_CREDIT_LIMIT_EXCEEDED',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_DUPLICATE: 'PRODUCT_SKU_DUPLICATE',

  // Advance
  ADVANCE_OVERDUE: 'ADVANCE_OVERDUE',
  ADVANCE_ALREADY_JUSTIFIED: 'ADVANCE_ALREADY_JUSTIFIED',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  OCR_PROCESSING_FAILED: 'OCR_PROCESSING_FAILED',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Map code → default HTTP status */
export const ErrorHttpStatus: Record<string, number> = {
  [ErrorCodes.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCodes.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCodes.AUTH_TOKEN_INVALID]: 401,
  [ErrorCodes.AUTH_MFA_REQUIRED]: 403,
  [ErrorCodes.AUTH_MFA_INVALID]: 403,
  [ErrorCodes.AUTH_ACCOUNT_DISABLED]: 403,
  [ErrorCodes.AUTH_FORBIDDEN]: 403,
  [ErrorCodes.VALIDATION_ERROR]: 400,
  [ErrorCodes.INVALID_INPUT]: 400,
  [ErrorCodes.INVALID_PHONE_FORMAT]: 400,
  [ErrorCodes.INVALID_RCCM_FORMAT]: 400,
  [ErrorCodes.INVALID_EMAIL_FORMAT]: 400,
  [ErrorCodes.INVALID_AMOUNT]: 400,
  [ErrorCodes.NOT_FOUND]: 404,
  [ErrorCodes.ALREADY_EXISTS]: 409,
  [ErrorCodes.CONFLICT]: 409,
  [ErrorCodes.EXPENSE_NOT_FOUND]: 404,
  [ErrorCodes.EXPENSE_ALREADY_APPROVED]: 409,
  [ErrorCodes.EXPENSE_CANNOT_BE_EDITED]: 409,
  [ErrorCodes.EXPENSE_AMOUNT_EXCEEDS_LIMIT]: 422,
  [ErrorCodes.EXPENSE_INVALID_STATUS_TRANSITION]: 422,
  [ErrorCodes.BUDGET_EXCEEDED]: 422,
  [ErrorCodes.BUDGET_THRESHOLD_REACHED]: 422,
  [ErrorCodes.BUDGET_NOT_FOUND]: 404,
  [ErrorCodes.BUDGET_PERIOD_OVERLAP]: 409,
  [ErrorCodes.SALE_NOT_FOUND]: 404,
  [ErrorCodes.SALE_ALREADY_PAID]: 409,
  [ErrorCodes.SALE_CANNOT_BE_EDITED]: 409,
  [ErrorCodes.SALE_INVALID_STATUS_TRANSITION]: 422,
  [ErrorCodes.SALE_NO_ITEMS]: 422,
  [ErrorCodes.PAYMENT_EXCEEDS_BALANCE]: 422,
  [ErrorCodes.PAYMENT_INVALID_AMOUNT]: 422,
  [ErrorCodes.CLIENT_NOT_FOUND]: 404,
  [ErrorCodes.CLIENT_CREDIT_LIMIT_EXCEEDED]: 422,
  [ErrorCodes.PRODUCT_NOT_FOUND]: 404,
  [ErrorCodes.PRODUCT_SKU_DUPLICATE]: 409,
  [ErrorCodes.ADVANCE_OVERDUE]: 422,
  [ErrorCodes.ADVANCE_ALREADY_JUSTIFIED]: 409,
  [ErrorCodes.FILE_TOO_LARGE]: 413,
  [ErrorCodes.FILE_TYPE_NOT_ALLOWED]: 415,
  [ErrorCodes.FILE_UPLOAD_FAILED]: 500,
  [ErrorCodes.OCR_PROCESSING_FAILED]: 500,
  [ErrorCodes.INTERNAL_ERROR]: 500,
  [ErrorCodes.SERVICE_UNAVAILABLE]: 503,
  [ErrorCodes.RATE_LIMIT_EXCEEDED]: 429,
};

/** Get the HTTP status for an error code (defaults to 500). */
export function getHttpStatus(code: string): number {
  return ErrorHttpStatus[code] ?? 500;
}
