/**
 * Notification types — maps to business events.
 */
export enum NotificationType {
  EXPENSE_TO_VALIDATE = 'EXPENSE_TO_VALIDATE',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  BUDGET_ALERT = 'BUDGET_ALERT',
  ADVANCE_UNJUSTIFIED = 'ADVANCE_UNJUSTIFIED',
  RECEIVABLE_OVERDUE = 'RECEIVABLE_OVERDUE',
  CASH_REGISTER_CLOSE_REQUIRED = 'CASH_REGISTER_CLOSE_REQUIRED',
  AI_ANOMALY_DETECTED = 'AI_ANOMALY_DETECTED',
  TREASURY_FORECAST_ALERT = 'TREASURY_FORECAST_ALERT',

  // Demande d'Achat (e-DA)
  DA_SUBMITTED = 'DA_SUBMITTED',
  DA_TO_PRICE = 'DA_TO_PRICE',
  DA_PRICED = 'DA_PRICED',
  DA_TO_VALIDATE = 'DA_TO_VALIDATE',
  DA_RETURNED = 'DA_RETURNED',
  DA_APPROVED = 'DA_APPROVED',
  DA_REJECTED = 'DA_REJECTED',
  DA_VALIDATED_TRANSMITTED = 'DA_VALIDATED_TRANSMITTED',
  DA_TAKEN_OVER = 'DA_TAKEN_OVER',
  DA_PROCESSING = 'DA_PROCESSING',
  DA_PROCESSED = 'DA_PROCESSED',
  DA_CLOSED = 'DA_CLOSED',
  DA_CANCELLED = 'DA_CANCELLED',
}

/**
 * Channels through which a notification can be delivered.
 */
export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
}
