export enum PurchaseRequestPriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  VERY_URGENT = 'VERY_URGENT',
}

export enum PurchaseRequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_VALIDATION = 'IN_VALIDATION',
  VALIDATED = 'VALIDATED',
  TRANSMITTED = 'TRANSMITTED',
  TAKEN_OVER = 'TAKEN_OVER',
  IN_PROCESS = 'IN_PROCESS',
  PROCESSED = 'PROCESSED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum PurchaseRequestApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
}

export enum PurchaseRequestDocumentType {
  DEVIS = 'DEVIS',
  FACTURE_PROFORMA = 'FACTURE_PROFORMA',
  CAHIER_CHARGES = 'CAHIER_CHARGES',
  IMAGE = 'IMAGE',
  FICHE_TECHNIQUE = 'FICHE_TECHNIQUE',
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  AUTRE = 'AUTRE',
}

export enum PurchaseRequestHistoryAction {
  CREATED = 'CREATED',
  SUBMITTED = 'SUBMITTED',
  PRICED = 'PRICED',
  SUBMITTED_TO_CIRCUIT = 'SUBMITTED_TO_CIRCUIT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED = 'RETURNED',
  VALIDATED = 'VALIDATED',
  TRANSMITTED = 'TRANSMITTED',
  TAKEN_OVER = 'TAKEN_OVER',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  REOPENED = 'REOPENED',
  COMMENT = 'COMMENT',
}
