export const PERMISSIONS = {
  EXPENSE_CREATE: 'expense.create',
  EXPENSE_READ: 'expense.read',
  EXPENSE_UPDATE: 'expense.update',
  EXPENSE_DELETE: 'expense.delete',
  EXPENSE_APPROVE_L1: 'expense.approve_l1',
  EXPENSE_APPROVE_L2: 'expense.approve_l2',
  EXPENSE_PAY: 'expense.pay',
  EXPENSE_CANCEL: 'expense.cancel',
  EXPENSE_EXPORT: 'expense.export',
  CASH_CLOSING_OPEN: 'cash_closing.create',
  CASH_CLOSING_READ: 'cash_closing.read',
  CASH_CLOSING_CLOSE: 'cash_closing.create',
} as const;

export const EXPENSE_PERMISSIONS = {
  CREATE: PERMISSIONS.EXPENSE_CREATE,
  READ: PERMISSIONS.EXPENSE_READ,
  UPDATE: PERMISSIONS.EXPENSE_UPDATE,
  DELETE: PERMISSIONS.EXPENSE_DELETE,
  APPROVE_L1: PERMISSIONS.EXPENSE_APPROVE_L1,
  APPROVE_L2: PERMISSIONS.EXPENSE_APPROVE_L2,
  PAY: PERMISSIONS.EXPENSE_PAY,
  CANCEL: PERMISSIONS.EXPENSE_CANCEL,
  EXPORT: PERMISSIONS.EXPENSE_EXPORT,
} as const;

export const CASH_CLOSING_PERMISSIONS = {
  OPEN: PERMISSIONS.CASH_CLOSING_OPEN,
  READ: PERMISSIONS.CASH_CLOSING_READ,
  CLOSE: PERMISSIONS.CASH_CLOSING_CLOSE,
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
