apiVersion: v1
kind: Namespace
metadata:
  name: caisseflow-staging
  labels:
    app.kubernetes.io/part-of: caisseflow
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: caisseflow-prod
  labels:
    app.kubernetes.io/part-of: caisseflow
    environment: production
